### ISSUE TITLE
Can't run raylib-bqn on macOS 

### ISSUE THREAD

**Issue by OliverM** [Brian-ED/rayed-bqn#23]
I'm trying to get raylib working on mac but I'm having issues. I've installed raylib via homebrew and the `dylib` is available at `/opt/homebrew/lib/libraylib.dylib`. I've updated my config.txt file to point at this location like this:

```
raylibPath:/opt/homebrew/lib/libraylib.dylib
bqn-libsPath:/Users/olivermooney/projects/rayed-bqn/src/imports/bqn-libs
```

But when I try to run the `DrawEllipse` example I get 
`Error: FFI: Failed to load library: dlopen(/usr/local/lib/libraylib.so, 0x0002): tried: '/usr/local/lib/libraylib.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libraylib.so' (no such file), '/usr/local/lib/libraylib.so' (no such file)`

It seems to be ignoring the setting and checking Linux-default locations instead. Am I doing something wrong? 

Thanks for the library, I'm really excited to try it!

**Comment by OliverM** [comment]
Hmm, I see the auto-generated `rayffi.bqn` file has the line 
```
r ⇐ MakeImporter "/usr/local/lib/libraylib.so"
```
and it looks like that file expects raylib version 5, based on lines 66-69, though the readme says to download 4.5? I bumped my raylib install to version 5, and set `r` to 
```
r ⇐ MakeImporter "/opt/homebrew/lib/libraylib.dylib"
```

And the error changed to a missing symbol error:
```
Error: FFI: Failed to find symbol: dlsym(0x84062110, DrawLineBezierQuad): symbol not found
```

**Comment by OliverM** [comment]
Just in case, I've tried it with both the current master branch and develop branch of `CBQN`. Same error on both.

**Comment by Brian-ED** [comment]
ooo this looks like i've spent too long on linux without testing other versions. I'm on it!

**Comment by Brian-ED** [comment]
Oh ofcourse. Ok so a few things, the docs are outdated i should probably just say latest version of raylib. second thing is i recently added the raylib auto parser to auto make rayffi.bqn, and i accidentally made it decide the path and never change it.
you can fix it on your end right now by running the "rayed-bqn/src/parseC_FFI_BQN/parseRaylibJson.bqn" and it should generate a working rayffi.bqn to your version of raylib no matter which it is. 
I'll fix it on my end, should be a ok-quick addition.

**Comment by Brian-ED** [comment]
I have decided that I should probably implement some sort of version picking from config, and have a separate place for rayffi.bqn since if you import raylib.bqn it automatically imports rayffi.bqn so no need to have rayffi.bqn at top level. It'd be nice since then i could keep all working versions of rayffi available, and windows users could still use a specific rayed-bqn version without needing to get a c compiler. Only release versions though ofc

**Comment by Brian-ED** [comment]
I also now figured out your `DrawLineBezierQuad` not existing error. When i ran the auto parser on version recent dev branch DrawLineBezierQuad was renamed to DrawSplieBezierQuad.

**Comment by Brian-ED** [comment]
I should add running the autoparser as a step on linux/mac. doing that should fix these sorts of issues.
The windows version will actually now be broken, so i wonder what the solution there will be. 
I should really get the raylib_parser.c reimplemented in BQN, i was working on that but it's slow progress. I'd expect to be done with that in a few weeks probably?

**Comment by Brian-ED** [comment]
I'll go to sleep soon. The issue of windows not having a c compiler inbuilt thing will be fixed by making a folder with different ffi release versions pre-parsed, so no need for C.
... or i'll finally get to making that parser in bqn :p

**Comment by Brian-ED** [comment]
I've refrenced needing C to parse rayffi.bqn as an issue here: #24
But since you probably have a C compiler you can run `rayed-bqn/src/parseC_FFI_BQN/parseRaylibJson.bqn` and that should fix your issue. Do tell me if you succeed so i can close the issue.
And thanks for your interest in the library :D

**Comment by OliverM** [comment]
It works!! I pulled from master, pointed my raylib entry in the `config.txt` file back to the hombrew location (`/opt/homebrew/lib/libraylib.dylib`), then tried running the parser. It fails if you try to invoke it outside of the script directory (e.g. running `BQN rayed-bqn/src/parseC_FFI_BQN/parseRaylibJson.bqn` fails complaining it can't find `raylib_parser.c`) but if you switch to the `parseC_FFI_BQN` directory and run the script from there it completes.

Now the `DrawEllipse` example launches successfully!

Thanks for all your help with it @Brian-ED 🙌

**Comment by Brian-ED** [comment]
perfect! sorry for the trouble, the recent parser has made stuff a bit unstable. I'll see if i can fix the relative path issue really quick, i'm pretty sure it's just BQN doesn't do •file.At before giving the file location to the C parser

**Comment by Brian-ED** [comment]
or well, the issue was actually just replacing `SHErr "cc"‿"raylib_parser.c"` with `SHErr "cc"⋈•file.At"raylib_parser.c"`

**Comment by OliverM** [comment]
Great! No need to apologise at all, it's great to have this wrapper! Do you accept PRs? I could update the readme to help out other Mac users once you're happy with any remaining tweaks?

**Comment by Brian-ED** [comment]
that would be amazing, PRs are welcome

**Comment by Brian-ED** [comment]
> or well, the issue was actually just replacing `SHErr "cc"‿"raylib_parser.c"` with `SHErr "cc"⋈•file.At"raylib_parser.c"`
it was a bit more than that but now that's done, neat
