### ISSUE TITLE
Some symbols not found on MacOS Arm in rayffi.bqn

### ISSUE THREAD

**Issue by DavidZwitser** [Brian-ED/rayed-bqn#6]
When compiling examples, the compiler wasn't able to find two symbols:
GenImageGradientLinear;
GenImageGradientSquare.

Throwing:
⟨ "{*:i8,i32,i32,i32,i32}" "GenImageGradientLinear" "i32" "i32" "i32" "{u8,u8,u8,u8}" "{u8,u8,u8,u8}" ⟩ Error: Failed to find symbol: dlsym(0x30851c8f0, GenImageGradientLinear): symbol not found"

This was using raylib 4.5.0 precompiled for macos, running on a M1 Pro chip on macOS Ventura 13.4.1.

After deleting these two lines and the whole program ran successfully!

**Comment by Brian-ED** [comment]
What i assumed happened was that raylib had a breaking change and removed them, i will fix this later today. Thanks!

**Comment by Brian-ED** [comment]
i actually do have a mac, i'll test on that in a few hours

**Comment by Brian-ED** [comment]
I decided to remove these functions from rayffi.bqn and re-implement them in pure bqn at raylib.bqn instead. way easier than actually finding out what caused the issue :p
(these will be added in next push after i test my implementations, but i'm done)
